### ISSUE TITLE
Some problems with ACCA

### ISSUE THREAD

**Issue by hemlok89** [MatteCarra/AccA#10]
Hello, I am using ACC module with latest Magisk module, on LineageOS 14.1. I have noticed some problems. I use Termux. I generally use acc -e 80%. But when I connect the charger next time, I have to manually run acc -e to start charging, then run acc -e 80%. Also acc -e 80 60 (keep battery percentage within a limit) does not work at all.

**Comment by VR-25** [comment]
This is not the ACC (backend) repository.
You should have opened the issue at https://github.com/Magisk-Modules-Repo/acc/ instead.

Anyway, you're misunderstanding and misusing these commands.

`acc -e #%` keeps charging enabled **until the given capacity is reached.**
Unless your system is rebooted, you have to reenable charging manually (`acc -e`) or automate the process with `Daily Job Scheduler` (module).

`acc -e 80 60` is an invalid command. There's no such syntax in the documentation.
What you want is `acc 80 60` (without `-e`).

By the way, you don't have to always run `acc -e 80%` when you need it to work. ACC auto-starts and does its job according to `/sdcard/acc/config.txt`.
