### ISSUE TITLE
Reset battery stats reverts to "false" upon selecting any battery profile

### ISSUE THREAD

**Issue by qzmp010** [MatteCarra/AccA#103]
When either "Reset battery stats..." options is set to "true" on the Dashboard tab, tapping on a battery profile on the Profiles tab reverts both "Reset battery stats..." options back to "false." 

Also enabling either "Reset battery stats..." options will deselect any enabled battery profile on the Profiles tab.

Expected behavior: "Reset battery stats..." options and battery profile selection should behave independently. This bug was not present on older versions.

Tested on OP7P and Galaxy S5 on ACCA version 1.0.24

**Comment by MatteCarra** [comment]
Thanks!
