### ISSUE TITLE
Unfortunately, ACCA has stopped.

### ISSUE THREAD

**Issue by ghost** [MatteCarra/AccA#104]
![Screenshot_2020-06-18-11-49-59](https://user-images.githubusercontent.com/37603562/84976239-fc38ad80-b159-11ea-8baf-ab98a9538158.png)

### LOGS
[logs-2020-06-18-11-53-53.zip](https://github.com/MatteCarra/AccA/files/4796167/logs-2020-06-18-11-53-53.zip)

[acc-logs.zip](https://github.com/MatteCarra/AccA/files/4808101/acc-logs.zip)

[DJS-logs.zip](https://github.com/MatteCarra/AccA/files/4808102/DJS-logs.zip)

**Comment by ghost** [comment]
@MatteCarra? 😅

**Comment by MatteCarra** [comment]
Can you please provide more details?
What were you doing when it crashed?
Were you using the bundled acc or a different version?
Thanks

**Comment by ghost** [comment]
@MatteCarra thanks for the reply but now I'm using the magisk module of ACC and it's work good on my phone.

**Comment by dchmelik** [comment]
I installed AccA from F-droid and have same problem on an Archos Elements 97 Platinum with an Android 4. Then I select share (to send you log?) but it said there's no log...

**Comment by squabbi** [comment]
@dchmelik can you provide which version of ACC you are running? Run `acc -v`.

**Comment by VR-25** [comment]
A clean install of the latest version from this repository should fix the issue.

**Comment by dchmelik** [comment]
I gave the particular pad/tab to a family member who lives somewhere else.  If they want to use AccA they'll ask me and I'll get back to you...
