### ISSUE TITLE
The phone doesn't charge if I close the app

### ISSUE THREAD

**Issue by Cyberavater** [MatteCarra/AccA#108]
ACC daemon stops running if close the app.
Expected behavior: It should run in the background even if I close it.

**Comment by squabbi** [comment]
Hi, if what you're experiencing is that the app shows the daemon is not running for a few seconds after running the app (and it was not previously running), that is typical behaviour that will be addressed soon.

If you'd like to check if the daemon is actually not running, run `acc -D` in the terminal for daemon status.

**Comment by VR-25** [comment]
https://github.com/MatteCarra/AccA/issues/114#issuecomment-663824318
