### ISSUE TITLE
Acca does not see the latest Acc

### ISSUE THREAD

**Issue by gjf** [MatteCarra/AccA#115]
According to Acca the latest version of Acc is 2020.7.19.
But in fact the latest is 2020.7.26 (both from https://github.com/VR-25/acc/ and https://github.com/Magisk-Modules-Repo/acc)
After manual upgrade Acca still shows 2020.7.19 as a latest version installed.

What's wrong?

**Comment by MatteCarra** [comment]
Vr25 forgot to tag the last two commits.
I already reported him the issue.
In the meantime: https://github.com/MatteCarra/AccA/releases/tag/v1.0.25
