### ISSUE TITLE
Pressing "Profiles" button causes crash

### ISSUE THREAD

**Issue by gjf** [MatteCarra/AccA#116]
Acca v1.0.25

Pressing "Profile" button causes an immediate crash.

Also crash happens when pressing "Export" in settings. "Import" seems OK.

**Comment by gjf** [comment]
Any comments why it's closed?
I have observed the same situation on Oneplus 7T Pro and Xiaomi Redmi 4X.
I am ready to give more information/logs if necessary.

**Comment by MatteCarra** [comment]
I'm sorry I didn't comment the issue.
I pulled release 1.0.25 as soon as you posted the issue and posted version 1.0.26 instead with the crash fixed.

**Comment by gjf** [comment]
Ah OK, thank you, will update right now.
