### ISSUE TITLE
Cannot install DJS

### ISSUE THREAD

**Issue by gjf** [MatteCarra/AccA#117]
Acca 1.0.26

Pressing scheduler button at the main window gives an alert "DJS should be installed".

When pressing "Install" the same alert appears again and again.

In fact DJS functions are not available.

**Comment by Hinfty** [comment]
Had the same issue after everything worked for a while and different version

**Comment by vilnitsky** [comment]
Djs installation stopped working too(

**Comment by adamallo** [comment]
I have the same issue. I also tried installing DJS directly from Magisk. It installed correctly and can get it's PID, but AccA still has the same issue.

**Comment by NomadicCore** [comment]
I have the same issue

**Comment by JuliusBairaktaris** [comment]
Same here

**Comment by Gronkdalonka** [comment]
Also error upon installing DJS, install script tries to chmod a file which is not there.


[install.log](https://github.com/MatteCarra/AccA/files/5313588/install.log)

**Comment by Ph0rk0z** [comment]
me as well, DJS never installs and tries to install again when clicked. djs daemon is checked when I go into settings. "develop" version never installs either even though it appears to download.

**Comment by sbstratos79** [comment]
Same issue. Installed DJS with Magisk. Acca still won't let me open the scheduler tab.

**Comment by arun54321** [comment]
Same problem. Cannot install djs. Even installed djs from magisk repo. still it doesn't work.

**Comment by ddddk79** [comment]
Same problem. On oneplus8t android11

**Comment by ssorgatem** [comment]
Same problem on Ulefone Armor 9, even after installing DJS with Magisk

**Comment by pagdot** [comment]
If djs is already installed is checked by checking if the installer is there in [Djs.kt#L98](https://github.com/MatteCarra/AccA/blob/develop/app/src/main/java/mattecarra/accapp/djs/Djs.kt#L98). Instead it should be checked if the binary exists using `which djsd > /dev/null` as stated in [djs Readme](https://github.com/VR-25/djs#online-djs-install).

**Comment by eegeeZA** [comment]
> If djs is already installed is checked by checking if the installer is there in [Djs.kt#L98](https://github.com/MatteCarra/AccA/blob/develop/app/src/main/java/mattecarra/accapp/djs/Djs.kt#L98). Instead it should be checked if the binary exists using `which djsd > /dev/null` as stated in [djs Readme](https://github.com/VR-25/djs#online-djs-install).

Good find. You should create a pull request with the changes. Remember to change not only `isDjsInstalled`, but also `initDjs` and `uninstallDjs`, as I see that they all rely on the faulty `installationDir`.

**Comment by pagdot** [comment]
Fixed some of the code locally, but couldn't get arsed to setup a proper Android dev setup, tried standalone android-sdk, but had problems with it.

I'll try to get a build later today and submit a PR if I've got it working

**Comment by MatteCarra** [comment]
any update @pagdot ?

**Comment by pagdot** [comment]
Sorry, I struggled because I didn't get djs to working when I tried it. I need to test it more. Additionally I need to make sure to call the initi script if necessary. I made a few mistakes at my first try. I try to continue this weekend

**Comment by blockberd** [comment]
Any update on that topic? I just found out about AccA and really want to use the DJS feature. I did the same things as above commenters

**Comment by pagdot** [comment]
I had issues that djs worked, but the command interface of AccA didn't work for me somehow most of the time.

**Comment by scrouthtv** [comment]
Maybe this is related to this DJS/A11 issue: https://github.com/VR-25/djs/issues/8

**Comment by pagdot** [comment]
No, I verified that DJS works by creating/modifying files with a djs job. I don't remember if I tried executing the acca commands myself, but I think I did and they didn't work either

**Comment by scrouthtv** [comment]
On Android 11?

**Comment by nortuzar** [comment]
Same problem here with ACCA 1.0.31, try all combinations but nothing works. Is there a manual fix to this?
Thanks for the great app

**Comment by MatteCarra** [comment]
Fixed.
