### ISSUE TITLE
(request) "charge to xyz%" menu

### ISSUE THREAD

**Issue by droid-jd** [MatteCarra/AccA#123]
It's just a minor inconvenience, and it likely doesn't bother anyone other than me. Truthfully, NOT a big deal in the slightest- the app is great!

Basically, when the menu pops up after opening " charge once to xyz% without restrictions", I keep finding myself tapping slightly off from "apply", and I don't realize that the menu closes and my charging current remains unchanged. Just wondering if it's possible to menu from closing if you tap outside the menu box. 

Like I said, not at all a big deal, just as minut polish point. Everything that the you and the other developers do here is amazing.

**Comment by squabbi** [comment]
I can make the dialog non-dismissable, or perahps create a little bit more padding around the "Apply" button!
I'll also change the toast message to something with more details too.

Thank you for the suggestion!

**Comment by droid-jd** [comment]
Awesome, thank you so much.
I know it's a minor issue, but I think it tidies things up a bit.
LOVE the app and what you and the other devs have done with it.
