### ISSUE TITLE
schedules created for DJS lead to error

### ISSUE THREAD

**Issue by Hinfty** [MatteCarra/AccA#125]
I have wondered why my DJS schedules only partly execute.
Now after trying them step by step ACC refuses to execute some.
For example AccA creates /dev/acca -s cooldown_capacity=101 (for disabled) 
This leads to an error and (in my case) also does not set the pause capacity and resume_c which are placed in the same line

**Comment by MatteCarra** [comment]
Please test with latest ACCA version.
