### ISSUE TITLE
ACC installation error/Ошибка установки ACC

### ISSUE THREAD

**Issue by Vitek14** [MatteCarra/AccA#126]
[Eng] As I understand from the logs, I don't have busybox, but I have it and many applications that need it work.
Can you tell me what needs to be done so that the error no longer shows?
(Sorry, I do not speak english well)

[Rus] Как я понял по логам у меня нету busybox, но он у меня имеется и многие приложения которые в нём нуждаются работают.
Можете ли вы подсказать что нужно сделать чтобы ошибку больше не показывало?

![Screenshot_2020-08-22-13-39-07](https://user-images.githubusercontent.com/59355907/90954518-29b11880-e475-11ea-9b19-733c5822ad6d.jpeg)

[install-tarball.sh.log](https://github.com/MatteCarra/AccA/files/5112234/install-tarball.sh.log)
[logcat_08-22-2020_13-05-05.txt](https://github.com/MatteCarra/AccA/files/5112235/logcat_08-22-2020_13-05-05.txt)

**Comment by MatteCarra** [comment]
Please test with latest ACCA version.

**Comment by VR-25** [comment]
Share your Android version and root method if the latest release also fails.
