### ISSUE TITLE
List alternatives on readme

### ISSUE THREAD

**Issue by eloyesp** [MatteCarra/AccA#132]
I found that listing alternative solutions on the readme is a very good practice, as it helps users make better choices (as that list usually explains differences between projects) and also helps developers join forces.

For example, there is an alternative software solution called [BatteryChargeLimit](https://github.com/sriharshaarangi/BatteryChargeLimit/) that I've found interesting. As far as I can tell, it does implement less features, but have a simpler UI.

**Comment by MatteCarra** [comment]
Thanks for your opinion.
BatteryChargeLimit and ACCA use completely different methods to achieve the same things.
There's no option to join forces sadly.

If you want to send a pull request for the readme with "alternatives" section, I will approve it.
Thanks a lot!
