### ISSUE TITLE
Bootloop after installing in MIUI even with acc v2020.10.01

### ISSUE THREAD

**Issue by ricardofago** [MatteCarra/AccA#134]
Hi everyone,

After a long period of acc causing MIUI devices to bootloop, [v2020.10.01 release](https://github.com/VR-25/acc/releases/tag/v2020.10.1) finally fixes it, but as AccA is bundled with an older version, installing the app still causes my device (Poco F2 Pro running MMX stable with Magisk 20.4) to bootloop, even though I switched acc to the most recent version in settings. I assume this happens because AccA still installs the older (embedded) version first. Can anyone confirm this?

Cheers!

**Comment by VR-25** [comment]
Yes, that's what happens.
You can avoid this by installing acc v2020.10.1+ before AccA (v1.0.26+ only).
