### ISSUE TITLE
Changes to profile not sticking

### ISSUE THREAD

**Issue by jordanade** [MatteCarra/AccA#135]
I change settings and hit the save icon. When I check they are saved, but later they revert back to the previous settings

**Comment by MatteCarra** [comment]
Thanks for the report.
Which changes are you trying to apply?
Be specific so I can reproduce.
Thanks a lot

**Comment by andiwirs** [comment]
I can confirm that issue. For me for example the max. temperature does not stick.
The default when i installed the app was 60°C. I changed it to 45°C hit save, closed the app, reopened, had a look at the settings and it was at 60°C again.

The procedure that helped for me was to change (in my case) the "default" profile to my liking and then apply the profile...

**Comment by jordanade** [comment]
Yep, same thing here. It works if I make sure to only edit and apply a
profile instead of the thing that pops up on the home screen.

**Comment by MatteCarra** [comment]
I can not reproduce the issue on latest version (from github).
Please test and close the issue if fixed

**Comment by andiwirs** [comment]
For me it seems to work now. See also #156
