### ISSUE TITLE
Chinese typos keep unfixed for versions

### ISSUE THREAD

**Issue by noobww** [MatteCarra/AccA#136]
the Chinese translation typo “阀值” keeps unfixed, although the correct spelling “阈值” was submitted many times on crowdin!

**Comment by MatteCarra** [comment]
Can you please tell me your crowdin username and the translation key for that translation?

**Comment by noobww** [comment]
> Can you please tell me your crowdin username and the translation key for that translation?

I am not sure what "the translation key" is;
but I am quite sure that you can safely replace ALL "阀值" with "阈值".

A lot of thanks for what you have been doing for us!

**Comment by MatteCarra** [comment]
I think this is fixed.
Can you confirm?
Close the issue if it's fixed
