### ISSUE TITLE
Crash after selecting profile

### ISSUE THREAD

**Issue by jordanade** [MatteCarra/AccA#137]
https://del.dog/ecutaruxiv

**Comment by squabbi** [comment]
Should be fixed in the latest releases, I discovered a similar bug, if not the same thing and was fixed by this commit: dab03dc
Make sure you grab v1.0.28 here: https://github.com/MatteCarra/AccA/releases

I'm going to close this now, but feel free to re-open if the issue persists on v1.0.28.
