### ISSUE TITLE
AccA doesn't write max current limit into DJS schedule

### ISSUE THREAD

**Issue by alaviss** [MatteCarra/AccA#139]
The culprit seems to be here:

https://github.com/MatteCarra/AccA/blob/afb21c79b336f69ab1b50357b569e2af371a9228/app/src/main/java/mattecarra/accapp/acc/ConfigUpdater.kt#L39-L66

There are no references to `getUpdateAccCurrentMaxCommand` here where I believe there should be.

**Comment by MatteCarra** [comment]
Thanks.
If you think you can fix issues like that you can create pull requests.
I will try to do this myself tho.
