### ISSUE TITLE
Unrecognized demon

### ISSUE THREAD

**Issue by lucenera** [MatteCarra/AccA#14]
Although the daemon is active (I checked from the command line), the app says it is not running.
![Screenshot_20190512-092457_ACCA](https://user-images.githubusercontent.com/35407790/57579193-fe313700-7498-11e9-901e-8db2a1d3c740.jpg)

**Comment by MatteCarra** [comment]
https://github.com/MatteCarra/AccA/releases/tag/1.0.6

**Comment by lucenera** [comment]
Now it's ok.
