### ISSUE TITLE
ACC Daemon Disables Battery Saver & Prevents Enabling of Battery Saver Mode

### ISSUE THREAD

**Issue by smudgered** [MatteCarra/AccA#141]
The ACC Daemon disables Battery Saver & prevents enabling of battery saver mode, either via status bar or directly in settings. 

Stopping the ACC Daemon removes this block, until phone is rebooted. Oreo AOSP - installation via ACCA front end.

(On tablet, also running Oreo, but in MiUI, this is not an issue as battery saver mode not available as an option, MiUI having its own implementation).

**Comment by smudgered** [comment]
Moved to ACC thread

**Comment by VR-25** [comment]
This should not happen with the latest version.
If the issue persists, refer to https://github.com/VR-25/acc#charging-switch .
