### ISSUE TITLE
[Feature Request] Dashboard - Battery voltage / battery amp remaining

### ISSUE THREAD

**Issue by git-greatguy** [MatteCarra/AccA#145]
Hello,

Could you add the current battery voltage and Amp remaining on the main app screen ?

Thanks for bringing to us this great app ;)

**Comment by MatteCarra** [comment]
Battery voltage could be displayed.
'Ah' remaining is simply Battery capacity * charge percentage.
Not sure if it's very useful.

**Comment by MatteCarra** [comment]
Battery voltage is now displayed.
