### ISSUE TITLE
Unable to turn on and off the daemon via status bar icon

### ISSUE THREAD

**Issue by chknatwork** [MatteCarra/AccA#159]
I'm using a OnePlus 7TPro upgraded to Android 11.

I'm on dark mode but when I try to turn off the accd manager, I can't turn it back on and just goes back to daemon stopped. I have to restart the phone to get it back up and running even if it isn't active.

Additionally, I've set AccA to stop charging at 100% but AccA doesn't seem to stop it.

**Comment by MatteCarra** [comment]
I think this problem is fixed
