### ISSUE TITLE
 the daemon can't be stopped/restarted by the app

### ISSUE THREAD

**Issue by binarynoise** [MatteCarra/AccA#163]
I can't stop the daemon via the app.
But if I kill the sleep sub-process manually, it will work.

It's quite annoying and it seems the daemon doesn't get updates of the settings either.

Samsung galaxy s10e, Android 10, rooted with Magisk latest stable

**Comment by bege10** [comment]
On Fairphone 3, /e/OS (based on FairphoneOS, LineageOS for microG, Android 10), Magisk 23001, ACC 2021.2.25, AccA 1.0.29 the daemon cannot be stopped but restarted.

[acc-logs-FP3.tar.bz2.zip](https://github.com/MatteCarra/AccA/files/6577567/acc-logs-FP3.tar.bz2.zip)
[logs-2021-06-01-17-42-16.zip](https://github.com/MatteCarra/AccA/files/6577569/logs-2021-06-01-17-42-16.zip)
