### ISSUE TITLE
Error Loop

### ISSUE THREAD

**Issue by Bogdans29** [MatteCarra/AccA#165]
![Screenshot_20210513-071128_AccA](https://user-images.githubusercontent.com/44641106/118080485-9630c680-b3ba-11eb-9104-ec69333fc14a.jpg)
![Screenshot_20210513-070412_AccA](https://user-images.githubusercontent.com/44641106/118080491-97fa8a00-b3ba-11eb-91ca-b2fa7e09048b.jpg)
![Screenshot_20210513-070349_AccA](https://user-images.githubusercontent.com/44641106/118080494-98932080-b3ba-11eb-9111-9375829a9d8c.jpg)

**Comment by MatteCarra** [comment]
Please test with latest ACCA version (from github)

**Comment by VR-25** [comment]
This is not an error.
It's just verbose of a loop.
