### ISSUE TITLE
Poco F1 not charging after uninstalling ACC.

### ISSUE THREAD

**Issue by AlippRosli** [MatteCarra/AccA#168]
Hi, I'm using Poco f1 android 11 with pixel experience rom running ACC v2021.2.25 (202102250). After installing ACC through my magisk app, this module gave me some problems like charging but my battery logo said its not.  I have tried to restore to default settings and uninstall it but my phone could not charge anymore. I need to reinstall this module and ACC to make it start charging again. Can anyone help me? What should I do to completely restore my settings and uninstall it?

**Comment by DerpSpears** [comment]
I would recommend a reinstall of your rom.

**Comment by VR-25** [comment]
This must be related to the PMIC bug described [here](https://github.com/lybdroid/poco-x3-pro/issues/1) and [here](https://forum.xda-developers.com/t/rom-official-arrowos-11-0-android-11-0-vayu-bhima.4267263/post-85119331).
Hence, it's not an acc issue.
I'll add this information to the documentation.

@lybxlpsv suggested: _"Temporary fix to reset is to boot into bootloader. Then back to System."_

This is **dangerous** for users who let their batteries discharge way too low.
Those whose phones are affected, may want to **actually use acc's _auto shutdown_ feature.**
