### ISSUE TITLE
max charge voltage still to 4200

### ISSUE THREAD

**Issue by meloalfa159** [MatteCarra/AccA#176]
hello, since last acc update the maximum charge voltage has been restored up to 4300 millivolt, but when i try to set it on acca it still shows me a 4200 mv limit. can you update the app? thanks

**Comment by VR-25** [comment]
[Done.](https://github.com/MatteCarra/AccA/commit/cbd0ba6777dd4914aa66dd6f22726bad219da980)

**Comment by VR-25** [comment]
[Done.](https://github.com/MatteCarra/AccA/commit/cbd0ba6777dd4914aa66dd6f22726bad219da980)
