### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by iPot** [MatteCarra/AccA#181]
So I granted the app root access to install something but I got an error like the one on the screenshot.
[install-tarball.sh.log](https://github.com/MatteCarra/AccA/files/6994196/install-tarball.sh.log)
[init.log](https://github.com/MatteCarra/AccA/files/6994197/init.log)
[install.log](https://github.com/MatteCarra/AccA/files/6994198/install.log)
[logcat.txt](https://github.com/MatteCarra/AccA/files/6994200/logcat.txt)

![Screenshot_20210817-002239_AccA](https://user-images.githubusercontent.com/36175287/129603035-2eb08dbe-3e8f-47b3-88f0-a27244a5aed4.png)

**Comment by VR-25** [comment]
According to the logs, the back-end (acc) was installed successfully.
The app should be able to detect that acc is installed.
Have you tried launching AccA again after clearing it from recents?

P.S., running `su -c acc -v` or `/dev/.vr25/acc/acc -v` on terminal should print acc's version.

**Comment by iPot** [comment]
The app works normally. I only use it for the pause and resume charging.
It's just that that error appears when I install the app for the first time but it goes to its menu like everything is normal.
The version is the 2021.8.4

I switched to the app coz the Magisk module coz the latest update for that makes my phone stop charging at 75% even though I have it set on 79%
