### ISSUE TITLE
ACC daemon randomly stops

### ISSUE THREAD

**Issue by v1993** [MatteCarra/AccA#183]
I'm not sure what information may be useful to you, so please tell me what I've missed.

I'm using AccA from F-Droid while having ACC installed via Magisk, on Huawei SCL-L21 with lineage OS 14.1 installed. The problem is that ACC daemon appears to randomly stop time to time, something that didn't happened in slightly older versions. Both AccA and ACC are updated to latest available versions. Logs in AccA don't appear to feature anything of interest.

**Comment by VR-25** [comment]
Right after the daemon stops, the output of `acc -l tail` would be helpful.
Thanks.

**Comment by v1993** [comment]
Is it a problem that I have ACC installed via magisk? Does AccA pick it up automatically?

I'll try to replicate this issue and send output.

**Comment by v1993** [comment]
Copied from AccA, appears to be identical to output of `acc -l tail`:

```
0: echo
288: sleep 0.3
46: read -A chargingSwitch
127: true
127: not_charging
267: grep -Eiq 'dis|not' battery/status
128: return 7
128: exxit
90: exitCode=7 
91: set +eux
```

**Comment by VR-25** [comment]
That's a classic.
The documentation states that exit code 7 means all charging switches failed to respond to the disable signal.
This is a kernel issue.
The workaround is disabling the _automatically cycle through switches_ setting in acca.

However, I'm not sure this is working as of now, as I rarely use acca.
For me, the terminal is still more efficient.
Latest acc > run `acc -ss` > pick working switch > done.

**Comment by v1993** [comment]
Thanks for explaining! Would be nice if there was some better indication from AccA what went wrong.
