### ISSUE TITLE
Low battery notifications can't be disabled

### ISSUE THREAD

**Issue by izomiac** [MatteCarra/AccA#184]
Since updating the app I've started receiving notifications when my battery reaches a certain threshold.  These happen repetitively (i.e. dozens or hundreds of times as the battery trickles downward and the notification is periodically dismissed) and can't be disabled since they're from the shell.  IMHO the whole feature should be removed since the constant notifications wake up the phone and drain battery life and there are already a plethora of apps that will alert at low battery levels for the minority of users that appreciate such a thing.  At the very least it should have a toggle in settings and use a notification channel other than shell.

**Comment by VR-25** [comment]
Refer to https://github.com/VR-25/acc/issues/108#issuecomment-900357973 .
