### ISSUE TITLE
Let acc handle CURRENT_NOW's negative sign

### ISSUE THREAD

**Issue by VR-25** [MatteCarra/AccA#186]
ACC now ensures that `CURRENT_NOW` is only be negative if the battery is not charging.

**Comment by nialone** [comment]
This statement. What is the problem? ))

**Comment by VR-25** [comment]
Context: some devices report negative current even when the battery is _charging_.
AccA _removes_ the negative sign even when the battery is _discharging_.
The app should do nothing, since acc itself adds/removes the sign as needed.
