### ISSUE TITLE
ACC doesnt work on A12

### ISSUE THREAD

**Issue by rookielucky** [MatteCarra/AccA#203]
/system/bin/sh: <stdin>[82]: acc: inaccessible or not found

**Comment by VR-25** [comment]
Install the latest acc version from Magisk.

When a systems lacks /sbin/ (recent Android versions do), one must reboot after installing acc to have it in the stand PATH. That's a Magisk requirement. Otherwise the /dev/.vr25/acc/ prefix has to be used. This is documented.
