### ISSUE TITLE
Log function not working properly

### ISSUE THREAD

**Issue by moxtron** [MatteCarra/AccA#204]
I encountered an issue with the logging-function in the app.

It seems to spitout information which is incorrectly processed. I saw shell commands abd paths in there. 
Check out the sample.

Maybe also include a way to export logs.
The current option only copies one line.
![Screenshot_20220113-200454.jpg](https://user-images.githubusercontent.com/80670284/149393364-9c5b0071-1a47-4eb4-be28-04bd3d8ddad4.jpg)

**Device Info**
- OS: Android 11 (OxygenOS)
-  Kernel: aarch64 Linux 4.19.113-perf+
-  Device: AC2003 (Nord)
-  ROM: AC2003_14_210813
-  Baseband: msm
-  Kernel: aarch64 Linux 4.19.113-perf+
-  CPU: Qualcomm Technologies, Inc LITO
-  RAM: 7442MiB

**Comment by VR-25** [comment]
That's actually the backend's (acc) log format.
The app does not have the ability to export logs. The command `acc --log --export` (or `acc -le`) does it.
