### ISSUE TITLE
Some questions and suggestions

### ISSUE THREAD

**Issue by friendlytherapist** [MatteCarra/AccA#22]
How do I update the app without loosing my data?
Can you add an in app update checker?
Can you create a default profile for each phone that is the manufacturers settings, as in what it would charge to if I completely removed ACC. Or a default check box next to each slider.

**Comment by MatteCarra** [comment]
Sorry for the late response.

A update notification mechanism should be already included.

The second idea is good.

**Comment by ChingghisKhan** [comment]
Hi, I am having issues installing ACCA:
Installation in Magisk seems corrupted.
Magisk tells me an update is availbale but installation fails.
Terminal tells me no update availble.
Please see screenshots.

Thanks
![Screenshot_2019-07-21-18-02-15-840_com topjohnwu magisk](https://user-images.githubusercontent.com/13459357/61594024-4d0cf280-abe7-11e9-8368-307437b0235a.png)
![Screenshot_2019-07-21-18-02-23-798_com topjohnwu magisk](https://user-images.githubusercontent.com/13459357/61594025-4da58900-abe7-11e9-8b58-a58c94112531.png)
![Screenshot_2019-07-21-18-02-30-106_com topjohnwu magisk](https://user-images.githubusercontent.com/13459357/61594026-4da58900-abe7-11e9-8c93-5ef11f8eb5de.png)
![Screenshot_2019-07-21-18-02-35-901_com topjohnwu magisk](https://user-images.githubusercontent.com/13459357/61594027-4da58900-abe7-11e9-9c51-6d742c8e7304.png)
![Screenshot_2019-07-21-18-03-14-746_com termux](https://user-images.githubusercontent.com/13459357/61594028-4da58900-abe7-11e9-8494-17bec979be3a.png)

**Comment by VR-25** [comment]
@ChingghisKhan, the upgrade command and back-end installer for AccA had issues. The latest updates fix these. ACC is already up. The app will follow soon. Once you install the new AccA, `acc --upgrade` will work as expected.

Note: the ACC Magisk module is uninstalled by AccA. If you see an ACC zombie in _Magisk Manager > Modules_, mark it for removal.

**Comment by ChingghisKhan** [comment]
Hi,

 

Thanks for your fast help, it works like charm now J

 

Best regards from Germany

 

Robert

 

Von: VR-25 [mailto:notifications@github.com] 
Gesendet: Sonntag, 21. Juli 2019 21:05
An: MatteCarra/AccA
Cc: Chighisskhan; Mention
Betreff: Re: [MatteCarra/AccA] Some questions and suggestions (#22)

 

@ChingghisKhan <https://github.com/ChingghisKhan> , the upgrade command and back-end installer for AccA had issues. The latest updates fix these. ACC is already up. The app will follow soon. Once you install the new AccA, acc --upgrade will work as expected.

Note: the ACC Magisk module is uninstalled by AccA. If you see an ACC zombie in Magisk Manager > Modules, mark it for removal.
