### ISSUE TITLE
"No Root" when using Kitsune Mask canary.

### ISSUE THREAD

**Issue by TYTheBeast** [MatteCarra/AccA#252]
My phone is rooted with Kitsune Mask 27001, yet AccA says "No Root"
What should I do?

**Comment by JSCSZZSS** [comment]
You need to manually set root permissions for ACCA in Kitsune

**Comment by TYTheBeast** [comment]
I had already done that, and it didn't work anyways, but either way I've switched to APatch and now AccA is working fine.
