### ISSUE TITLE
App not working 

### ISSUE THREAD

**Issue by bridges86406** [MatteCarra/AccA#26]
Pixel 3XL currently on May update and Magisk 19.2 Canary (19203).

When I install this app on the latest beta it tells me that the daemon is not running although it is. Did I miss something in the install?

**Comment by breucode** [comment]
I have the same Problem on Magisk 19.3 on the latest LineageOS for beryllium.

**Comment by MatteCarra** [comment]
The procedure should be ok.

I'm preparing for 3 big exams and I plan to continue developing the app once they are all finished.

You could try to install acc from the magisk repo

**Comment by VR-25** [comment]
@bridges86406, @breucode,
- Did you install `ACCApp 1.0.8` and `ACC 2019.6.8`? These are the latest versions (time of this writing).
- Has ACCApp been granted root access?
- Did you try clearing the app's data?

**Comment by MatteCarra** [comment]
I'm closing this until we have more details.
All compatibility issues should be solved with next builds.
