### ISSUE TITLE
Wireless charging

### ISSUE THREAD

**Issue by laptapper1** [MatteCarra/AccA#28]
It seems like acca doesn't handle wireless charging well on xiaomi mi 9 , it's switching on off on off... while around charging limit.
I think it's bad for battery life.

**Comment by VR-25** [comment]
Please, upload `/sdcard/acc-logs-*.tar.bz2` after running `acc --log --export`.

**Comment by laptapper1** [comment]
Hi
Here is the log
[acc-logs-cepheus.tar.zip](https://github.com/MatteCarra/AccA/files/3421951/acc-logs-cepheus.tar.zip)
Hopefully you can advice me to get it working

**Comment by laptapper1** [comment]
Did you've found out which setting is working ?
