### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jmtrotz** [MatteCarra/AccA#29]
This isn't a big deal, but I noticed a typo while setting the on plugged option. I assume it's supposed to say "Leave blank to disable", but instead it says "Leave black to disable." 

![Screenshot_20190608-010704](https://user-images.githubusercontent.com/17212510/59142349-f925b180-898a-11e9-884d-73808b41e767.png)

**Comment by MatteCarra** [comment]
Thanks a lot. Feel free to correct it if you know how to do it.

I'm preparing for 3 big exams.
I plan to continue developing the app once they are all finished.

**Comment by VR-25** [comment]
@MatteCarra, I corrected that 9 days ago.
@jmtrotz, the next release will include this change.
Thanks
