### ISSUE TITLE
App freeze when trying to apply limit for one charge.

### ISSUE THREAD

**Issue by davidgro** [MatteCarra/AccA#34]
When I attempt to use "Edit limit for one charge", the moment I tap Apply ACCA freezes - it doesn't even dismiss the dialog. It does however appear to apply the setting.   

Also, a bit after reaching the set one-time-limit, ACC crashes and the phone just discharges, but that may be an ACC bug, I'll try it from commandline.

ACCA 1.0.8
ACC 2019.6.20
Phone: LG V20 (US996) with Oreo 8.0.0

**Comment by VR-25** [comment]
`acc -f` runs in foreground. The app mistakenly "thinks" it should wait for the process to finish.
