### ISSUE TITLE
Can't read it's own config files apparently

### ISSUE THREAD

**Issue by ovizii** [MatteCarra/AccA#36]
Can't read it's own config files apparently. Tried version 1.0.6 and 1.0.8

![Screenshot_20190624-081631_ACCA](https://user-images.githubusercontent.com/837902/59996143-cbfb2380-9659-11e9-9ae8-d62ec2d8362d.png)

**Comment by squabbi** [comment]
Try running `acc -s r` to restore the default configuration.

**Comment by VR-25** [comment]
The latest acc uses a new config filename (acc.conf). That's the problem.
I totally forgot the app! :-o

**Comment by ovizii** [comment]
sorry guys I've never touched the command line of this magisk module due to using the app. 
I guess I'll just wait for a newer version of the app then :-) 

Feel free to close this issue once the app knows about the new file name.

**Comment by VR-25** [comment]
Meanwhile, you can downgrade acc to [201906200](https://github.com/VR-25/acc/releases/download/201906200/acc-201906200.zip). If you're doing that, run `acc -s wakeUnlock` afterwards.

**Comment by MatteCarra** [comment]
Fixed: https://github.com/MatteCarra/AccA/releases/tag/v1.0.9

**Comment by ovizii** [comment]
Thanks, works perfectly.
