### ISSUE TITLE
Crash on notifications pull-down

### ISSUE THREAD

**Issue by elahn** [MatteCarra/AccA#37]
AccA crashes upon pull-down of the notifications bar from the top of the screen, with any app open or just at the launcher.

Occurs on 1.0.8 and v1.0.9, does not occur on 1.0.3.

Device: kltedv (Samsung Galaxy S5 SM-G900i)
LineageOS 15.1-20190224-NIGHTLY-kltedv
Ares-Kernel-beta-v1.4

Log: [2019-06-25-17-45-50-0.txt](https://github.com/MatteCarra/AccA/files/3324184/2019-06-25-17-45-50-0.txt)

**Comment by MatteCarra** [comment]
Thanks a lot for the log file.
I'm fixing it

**Comment by MatteCarra** [comment]
Note: the crash has been fixed, but the AccProfileTitle has been disabled for now because I've no time to code now
