### ISSUE TITLE
updateBatteryInfoRunnable is not paused when app is paused

### ISSUE THREAD

**Issue by MatteCarra** [MatteCarra/AccA#38]
updateBatteryInfoRunnable in DashboardViewModel is not paused when app is paused
https://github.com/MatteCarra/AccA/blob/60477ad6feac8b912f5bb030750f4f96375d35cf/app/src/main/java/mattecarra/accapp/fragments/DashboardViewModel.kt#L18

**Comment by squabbi** [comment]
Sometimes when switching fragments, the runnable is not stopped. Looking to see a more sturdy way of detaching the handlers.

**Comment by MatteCarra** [comment]
It should be fixed with commit 89119697368268280de50c40024f5274144b6f57
