### ISSUE TITLE
Updating the current profile will not apply new settings

### ISSUE THREAD

**Issue by squabbi** [MatteCarra/AccA#44]
Should it be kept that way? Or have something that will re-apply the profile of it has been edited.

**Comment by MatteCarra** [comment]
Nice question.

I don't it should be automatically applied, but I think that the green check that marks that a profile is active should be deselected if it has been changed

**Comment by squabbi** [comment]
I reckon we can have that as an option when we further develop the app to have some user preferences.

But yeah, for now we might just do that (have it deselect).
