### ISSUE TITLE
voltage limit value error

### ISSUE THREAD

**Issue by cxyzzz** [MatteCarra/AccA#51]
the accepted voltage range is 3920-4349mV

**Comment by VR-25** [comment]
The range `3500-4350 millivolts` reported by the app is actually correct.
I forgot to change the `acc -v` output (3920-4349).
I'm releasing a new acc version soon. Run `acc --upgrade` (or -u) to download and install the update.
Thanks

**Comment by cxyzzz** [comment]
@VR-25 :grinning:Looking forward to your update

**Comment by cxyzzz** [comment]
update to dev 2019.07.21 `acc -v 3900` is ok,but ACCA still prompts an error.

**Comment by VR-25** [comment]
That's a different issue altogether.
I already found where the problem is, though.
A new AccA version will be up once I'm done fixing another acc issue.
