### ISSUE TITLE
Charge till 90% keeps charging bug

### ISSUE THREAD

**Issue by dkoek** [MatteCarra/AccA#52]
Since acc doesn't install by Magisk but directly from acc apk 1.0.13 The app doesn't stop or limit charging. Deinstall and reinstall doesn't help the problem. 
![Screenshot_20190721-225646_ACCA](https://user-images.githubusercontent.com/8331530/61597034-53ad6100-ac0b-11e9-9538-cfaafcc35671.png)

**Comment by MatteCarra** [comment]
Try to delete app data and to install latest version: https://github.com/MatteCarra/AccA/releases/tag/v1.0.14

**Comment by VR-25** [comment]
@dkoek, what's the output of `su -c acc -s` after applying that profile?

**Comment by dkoek** [comment]
Deleted data and cache. 
Sorry don't know where to install the zip file of the 1.0.14 version . Till now I used the apk file.
