### ISSUE TITLE
chagingSwitch has no effect

### ISSUE THREAD

**Issue by alpha-and-omega** [MatteCarra/AccA#56]
Setting chagingSwitch=FILE DEFAULT_VOLTAGE STOP_VOLTAGE in applyOnPlug/applyOnBoot has no effect (probably overwritten by general chagingSwitch setting)

**Comment by VR-25** [comment]
That use case is invalid - wrong syntax.
The correct syntax is `applyOnPlug=FILE:VALUE`. The same applies to _applyOnBoot_.
