### ISSUE TITLE
Voltage Control File Select

### ISSUE THREAD

**Issue by droid-jd** [MatteCarra/AccA#63]
When I attempt to select a Voltage control file, I am unable to see the actual file being selected, or the options available to me. This happened in both V. 14 and V. 15 of the app. I believe it is a design issue only, and may not require the submission of a log, but I have attached screenshots to explain what I'm experiencing.
On the Portrait screenshot, I am unable to scroll through the other options for a Voltage Control file.
![Screenshot_20190822-161737_ACCA](https://user-images.githubusercontent.com/10563952/63547128-775d1300-c4f9-11e9-8258-38152ef27098.png)

On the Landscape screenshot, I can see that there are five (5) options for voltage control files, but I cannot actually see what they are.
![Screenshot_20190822-162243_ACCA](https://user-images.githubusercontent.com/10563952/63547129-775d1300-c4f9-11e9-9d1e-ff4dfe34d15d.png)

I have not seen anyone else report this issue in the XDA thread, and the quick browsing of "related issues" on github did not produce any immediately obvious results. 
I am running LineageOS 16 on my OnePlus 6T, in case that information is helpful. 

By contrast, the Capacity Control/Charging Switch menu pops up perfectly for me, with clear listings of the available switch files. 
![Screenshot_20190822-163033_ACCA](https://user-images.githubusercontent.com/10563952/63547488-45987c00-c4fa-11e9-9903-624dba40ecf1.png)

If there is anything else you need from me, please do not hesitate to let me know.

**Comment by MatteCarra** [comment]
Thanks a lot for the very detailed bug report.
I've never seen this issue and I can't reproduce it on my device (OnePlus 6, OxygenOS).
My hypothesis is that it's a strange LOS bug, but I will check if I can do anything about it.

![image](https://user-images.githubusercontent.com/11074527/63550323-b6f42100-c532-11e9-9ea0-5929c6eec368.png)
![image](https://user-images.githubusercontent.com/11074527/63550340-bbb8d500-c532-11e9-9586-89fae51789e2.png)

**Comment by droid-jd** [comment]
Happy to help! Been using the app and module for some time now, so it's
nice to be able to contribute something back.

By the way, seeing as we have similar devices, are you able to get battery
idle mode or voltage limiting working?
Apologies if this isn't the appropriate venue to discuss this.

**Comment by MatteCarra** [comment]
None of them sadly.
These features depend on the kernel and oneplus kernel does not seem to support them.
