### ISSUE TITLE
Translation suggestions for Chinese

### ISSUE THREAD

**Issue by iCassius** [MatteCarra/AccA#67]
>     <string name="cooldown_capacity">开始冷却阀值:</string>
>     <string name="resume_charge">恢复充电阀值:</string>
>     <string name="stop_charge">停止充电阀值:</string>
There is no word “阀值” , the correct is "阈值"

**Comment by iCassius** [comment]
# #68

**Comment by squabbi** [comment]
Thank you for submitting those translations! We'll be sure to incorporate them into our next release. :)
