### ISSUE TITLE
Acc daemon stops when the app is closed

### ISSUE THREAD

**Issue by paypur** [MatteCarra/AccA#72]
upgrading to 1.0.19 has caused this issue and downgrading to 1.0.14 fixes it

Edit: Now it doesn't work flatout after the first few seconds of manually restating the daemon. Ill try to attach a log when I have time

Edit 2: so it does work, but only if i charge off of my computer. I'm using a 1+ 6t with the stock charger

**Comment by MatteCarra** [comment]
I can't reproduce your bug.
How do you check if daemon is running when the app is in background?
You should use 'accc -D' from terminal.

**Comment by VR-25** [comment]
@paypur, also, please send us `/sdcard/acc-logs-*.tar.bz2` after running `acc -l -e`.

**Comment by paypur** [comment]
> @paypur, also, please send us `/sdcard/acc-logs-*.tar.bz2` after running `acc -l -e`.


[logs.zip](https://github.com/MatteCarra/AccA/files/3758853/logs.zip)

**Comment by deulizealand** [comment]
I have face that to , but when i test it. (start and stop limit) it work as well . Also when you stop the service and reopen the app.  The service doesnt start. It's differrnt when you start the service and reopen the app.  Service is start but there is some delay to check it.  Hope you understand what i mean .

**Comment by paypur** [comment]
After further testing acc does work, but is goes over my set limit by a couple of percent.
