### ISSUE TITLE
Failed to Install

### ISSUE THREAD

**Issue by jasonkhoo87** [MatteCarra/AccA#74]
Device: Sony Xperia M
Android Version: 4.1.2
Root Type: SuperSU
Busybox: v1.24.1-Stericson installed in /system/xbin

Using acc app to install and prompted error message to send the log, attached the log in this post.

[acc-data.zip](https://github.com/MatteCarra/AccA/files/3812453/acc-data.zip)

**Comment by VR-25** [comment]
Try the latest pre-release: https://github.com/VR-25/acc/releases/ .
