### ISSUE TITLE
When Open Acc, it hang the phone then reboot after a while

### ISSUE THREAD

**Issue by jasonkhoo87** [MatteCarra/AccA#75]
Phone: Samsung GT-I9082
Android: Android 4.2.2
Busybox: v1.28.3-Stericson installed in /system/xbin
Root Type: SuperSU

I attached the log in this post.
[acc-data.zip](https://github.com/MatteCarra/AccA/files/3812475/acc-data.zip)

**Comment by VR-25** [comment]
Partly related to issues #74 and #78

**Comment by VR-25** [comment]
Try the latest pre-release: https://github.com/VR-25/acc/releases/ .
