### ISSUE TITLE
ACC installation failed in android 5.1 AOSP

### ISSUE THREAD

**Issue by ghost** [MatteCarra/AccA#78]
Logcat:https://drive.google.com/file/d/10lV0aFdP6Dccp4pEylPU0s1flvhNb4sQ/view?usp=drivesdk

ACCA version 1.0.20

**Comment by VR-25** [comment]
#74

**Comment by VR-25** [comment]
#74

**Comment by VR-25** [comment]
Potential fixes applied (next release).
