### ISSUE TITLE
Acc Daemon wont start

### ISSUE THREAD

**Issue by Justdigit** [MatteCarra/AccA#83]
Device:Ibasso DX160 
Android: Android 8.1
Root Type: Magisk

The daemon won't start at. I can't install the bare (termux version) acc version. Because then I get a bootloop. As there is no Twrp for my device it's difficult to remove the module.

I have tried al versions non of them work.

[LOG FILE](https://gofile.io/?c=3XglPr)

**Comment by VR-25** [comment]
This device's chipset is unfriendly to custom charging control.
If you're ready for some testing, contact me on Telegram - https://t.me/vr25xda/ .

**Comment by squabbi** [comment]
Issue unrelated to ACCA and has been inactive for a while now.
