### ISSUE TITLE
Battery level displayed in ACCA of by about 3-5%

### ISSUE THREAD

**Issue by undermark5** [MatteCarra/AccA#9]
I'm running Google pixel 3 with latest versions of the app and Acc installed. Updated app potential cause, but not sure.

**Comment by VR-25** [comment]
There's a debate on whether we should show the true (hardware) values over software-masked values. We're currently using the first.

acc -i is more accurate than the system in this regard. Thus it's safe to say that system is of by 3-5%, not the battery management subsystem itself.

**Comment by undermark5** [comment]
That makes sense.
Though it is somewhat confusing when I've got it set to stop charging at 85% and it stops charging at about 80% (as shown by the battery indicator).
Perhaps if there is a debate over what should be shown/used, it would make sense to provide a choice to the user if possible.

**Comment by VR-25** [comment]
The `dumpsys battery` command doesn't always work. Thus, using values provided by the system would be a curse, rather than a potential solution.

My idea is implementing a capacity tolerance feature (e.g., capTolerance=+5). What are your thoughts on that?

**Comment by undermark5** [comment]
Should work out just fine I think.

**Comment by MatteCarra** [comment]
Check out the new acc config file.
Your issue should be now solved!
