### ISSUE TITLE
AccA not working with acc v. 202003100 or later

### ISSUE THREAD

**Issue by pizzamx** [MatteCarra/AccA#93]
AccA version: latest
acc version: 202003100 or 202003110
Device: Google Pixel 3

Everything was find until I decided to upgrade to Mar 10 release to address my Pixel 3 percentage sync issue. I upgrade through AccA, and it reports failure, and shows acca is not running. However by running shell command and some charge tests I can see the new version is up and running.

**Comment by MatteCarra** [comment]
The new build should solve this issue.
Please re-open if you still have problems when the new build will be out
