### ISSUE TITLE
This app has never worked properly for me

### ISSUE THREAD

**Issue by rudolphos** [MatteCarra/AccA#94]
I was using this on Android 9 and now on Android 10. Started charging from 13%.
I have set temperature cooldowns. So it charges until 29% and them stops until I reconnect it manually. I doesn't start charging again.
I'm using QuickCharge 3. So temperature cooldown is VERY necessary.
My phone is rooted with latest magisk, greenify, kernel adiutor and L-speed tweaks.

**Comment by VR-25** [comment]
1) Install the latest app version: https://forum.xda-developers.com/attachment.php?attachmentid=4968491&d=1583865090

2) Upgrade ACC: https://github.com/VR-25/acc/releases/download/202003110/acc-202003110.zip

**Comment by squabbi** [comment]
Closing this issue as it has been inactive for a while.
